### ISSUE TITLE
Data Ingest Interface

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-data-services#1]
Need a way of requesting data to be staged by the ADES within the SPS

**Comment by mike-gangl** [comment]
There are several interfaces:
1. 'traditional' download and ingest
2. CNM based ingest from SPS processing
3. User upload (e.g. an application developer) needs to store some data for future processing

1. is a known cumulus proess
2. can be seen here: https://unity-sds.github.io/unity-architecture/#/2.%20Unity%20Diagrams/Algorithm%20Execution/HOME and is similar to existing CNM mechanism
3. Needs some plumbing hooked up and requires some metadata from the user.

**Comment by mike-gangl** [comment]
i'd like to close this epic and open up more actionable ones. please see https://docs.google.com/spreadsheets/d/1ZMJh2IjJcpqL4ZX4uCEjkZhPIvjHwF_iERBD0rjAtk0/edit#gid=555044656 which details:

- Ingest in place capability for Unity Generated Data Products via CNM

We have other features/requests for uploading data that are uncommitted (e.g. we need to plan when we want to add that functionality).

**Comment by ngachung** [comment]
Close in favor of new actionable epics.
https://github.com/unity-sds/unity-data-services/issues/31
