### ISSUE TITLE
Evaluate PDS data model with respect to satisfying Unity requirements

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#10]

**Comment by seanhardman** [comment]
Requirements UNI-REQ-317 and UNI-REQ-318 are associated with interfaces to an ingestion interface but they do reference cataloging metadata pertaining to ingesting of science data files and their associated files. In addition, requirements UNI-REQ-320 and UNI-REQ-321 are associated with capturing provenance metadata. Data associated with these four requirements can be supplied by Collections and Data Products generated in conformance with the PDS4 data model. The work-to-go involves mapping the PDS4 attributes into the Unity DS data model which will be based on the CMR/UMM data model.
