### ISSUE TITLE
As a user, i want to be able to specify the output collection name to I want when requesting workflow execution

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-data-services#105]
* no -predefined - collections needed
* Input to the job process request
* maps to the a path in the destination S3 Bucket

**Comment by mike-gangl** [comment]
This would need to be an option in the workflow execution (e.g. in the initial WPS-T request) but the action for catalog/staging needs to know this collection as well.

**Comment by ngachung** [comment]
DS automatically creates collection upon ingest. See related https://github.com/unity-sds/unity-data-services/issues/43
