### ISSUE TITLE
As a user, i want request data from a DAAC using Earthdata Login for data access

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-data-services#109]
Project can pull data from a DAAC using an earthdata login for access
- How are EDL params captured/stored? (SSM?)
- How are they referenced
- stand alone task: Could be used to ingest data into unity catalog or could be used to process the data

**Comment by ngachung** [comment]
DAAC data download has been implemented
https://github.com/unity-sds/unity-data-services/issues/119
https://github.com/unity-sds/unity-data-services/pull/132
