### ISSUE TITLE
Develop prototype data model for Unity

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#11]

**Comment by seanhardman** [comment]
The Unified Metadata Model (UMM) will be the basis for the Unity DS Data Model. The model is very mature at this point and captures the primary concepts that Unity wants to track. The Unity DS Data Model will be extended to meet our requirements. This will include extensions for tenant/venue isolation, archive delivery tracking, planetary data support, metrics, etc.

**Comment by seanhardman** [comment]
The initial draft of the Data Model for Unity Prototype 0.2 has been posted to Google Drive: https://drive.google.com/drive/folders/1g6mxvTdWxIoY-rIve-BNui-GiUclPjP8
