### ISSUE TITLE
Add STAC support to stage in task implemented from MAAP HEC project

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#121]
https://github.com/jplzhan/maap-ci-stage-io/blob/main/stage_in.py

**Comment by wphyojpl** [comment]
https://github.com/jplzhan/maap-ci-stage-io/blob/main/stage_in.py
Ask James for sample input json.

**Comment by wphyojpl** [comment]
- integrity check function
- caching function
- download from http, S3, MAAP(required?), DAAC(not implemented).

**Comment by wphyojpl** [comment]
sample input json:
```
{"cache_dir": null, "cache_only": false, "input_path": {"url": ["https://raw.githubusercontent.com/unity-sds/unity-example-application/main/process.ipynb"]}}
```
cloned repo: https://github.com/unity-sds/unity-ci-stage-io

**Comment by mike-gangl** [comment]
need to work with @mcduffie to understand how this stage in interfaces with MAP HEC work so far.

**Comment by wphyojpl** [comment]
This is no longer relevant. Ended up not using MAAP HEC directly, but took some of their ideas. Closing it.
