### ISSUE TITLE
Catalog task should check if collection is defined before submitting CNM messages

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#180]
While testing catalog task, I realized I used a non-existence collection in stage out so the catalog task waits forever and CNM messages are not processed. Probably worth checking up front if the collection is defined first.

if not we should either A) return an error or B) create the collection at runtime.

**Comment by mike-gangl** [comment]
@rtapella Lots of usability stuff here. If we had a front end, they could "select" an existing collection when submitting a job, or we could "create new collection" if they wanted something new.

The unity-sds-client (unity-py) could also have some checks.

**Comment by rtapella** [comment]
Yeah I am torn on whether to have a mini browse/search UI for collections in the job-submission form vs. having a way to search in a dedicated data-browser (e.g. DataDrive) and then paste a collection ID in to the form. It probably does need to validate existing Collections and have some basic auto-complete.

**Comment by ngachung** [comment]
The catalog task refers to the yellow Data Catalog box in https://lucid.app/lucidchart/8cfdfeb4-f244-4a38-b574-fde8c7c1feed/edit?invitationId=inv_872ddff4-3919-4423-b821-1efc12e7b000&page=jSXkb6Xvop-p#

**Comment by wphyojpl** [comment]
I remember we talked about referencing existing collections so that a new collection (a different version) is collected on the fly. 
I could not recall if we went ahead with that idea. But this is similar to that. 
We would need some info to create an entirely new collection on the fly if we are not referencing similar collections. 
```
        dapa_collection = UnityCollectionStac() \
            .with_id(temp_collection_id) \
            .with_graule_id_regex("^test_file.*$") \
            .with_granule_id_extraction_regex("(^test_file.*)(\\.nc|\\.nc\\.cas|\\.cmr\\.xml)") \
            .with_title("test_file01.nc") \
            .with_process('stac') \
            .with_provider('unity') \
            .add_file_type("test_file01.nc", "^test_file.*\\.nc$", 'unknown_bucket', 'application/json', 'root') \
            .add_file_type("test_file01.nc", "^test_file.*\\.nc$", 'protected', 'data', 'item') \
            .add_file_type("test_file01.nc.cas", "^test_file.*\\.nc.cas$", 'protected', 'metadata', 'item') \
            .add_file_type("test_file01.nc.cmr.xml", "^test_file.*\\.nc.cmr.xml$", 'protected', 'metadata', 'item') \
            .add_file_type("test_file01.nc.stac.json", "^test_file.*\\.nc.stac.json$", 'protected', 'metadata', 'item')
```
