### ISSUE TITLE
[Bug]: Stage out will report to CWL success even if AWS credentials fail

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-data-services#191]
See the attached [test_cwl.log](https://github.com/unity-sds/unity-data-services/files/12149512/test_cwl.log) log file. When running the UPLOAD command without proper AWS credentials success is reported by cwl-tool despite exceptions in the Python code.

**Comment by wphyojpl** [comment]
Hi, 
It's currently just logging the errors. 
```
        if len(errors) > 0:
            LOGGER.error(f'some errors while uploading granules: {errors}')
        LOGGER.debug(f'dapa_body_granules: {dapa_body_granules}')
        uploaded_item_collections = ItemCollection(items=dapa_body_granules)
        return json.dumps(uploaded_item_collections.to_dict(False))
```
I'm not sure if it throws an error before parallelization. 
The assumption is to ignore the failed granules as we are uploading many granules in 1 job.

The easy solution is to throw an error if there is 1 failure. 

The workaround that I am thinking is to return both, and cwl needs to decode and check the details. 
```
{
    success: {Feature Collection which has item},
    failures: {Feature Collection which has item}
}
```
But it kind of breaks STAC format. We can do something like this
```
{
   "type": "FeatureCollection", 
   "features": [
           {succeeded Feature Collection which has items},
           {failed Feature Collection which has items},
     ]
}
```
Currently, the errors are listed for each file. 
```
some errors while uploading granules: [{'href': '/tmp/outputs/./summary_table.json', 'error': 'Unable to locate credentials'}]
```
It needs to be updated so that if 1 file fails, the entire granule fails. 
We'll need a place to store the errors like above. 
I can add them in `properties` as custom metadata. 

But all of that means whoever is using this needs to parse and pass only succeeded feature collection to catalog stage. 
It also needs to handle the errors.

**Comment by mike-gangl** [comment]
i think we have a few options here, if "upload" fails to upload _any_ granules, it should error out and the CWL process should stop.

There are 2 scenarios that might need different handling:
1. There are only a few files to upload after a job completes, in this case i think failing when any of them fail to upload is the right choice.
2. There are thousands of files after a batch job, in this case, i think a 'partial success' is a decent approach,  but that's complicated to deal with.

There are also times where step one, failing isn't ideal. If the compute takes a long time, there isn't a good reason to re-compute when all we want to do is run the stage-out workflow again. 

It almost seems like we want the ability to "retry" a step in the processes (here, stage-out, etc) with the failed granules. This could be a workflow we execute with stage-out and the "failed" list of granules. obvious concerns are "how do we get that list of failed granules to the user" and how are the referencing things on an ephemeral store (EFS, EBS, etc) without absolute references.

**Comment by mike-gangl** [comment]
i should clarify, for scenarios 1 and 2 above, it should be completely up to the _user_ to decide if they "fail on any" errors.

**Comment by wphyojpl** [comment]
After discussing with Nga, we'll tweak our stage-out a bit. 
1. After each upload, it will attempt a "re-try"logic based on the error. 
    1. It will not re-try if it's invalid or missing creds or other permanent errors. 
    2. How many times it will be re-tried and the delay between each re-try comes from config like Stage-in. 
1. If at least 1 file in a granule fails, the whole granule is assumed to have failed to stage-out. 
2. 2 files will be written to the temporary location that is provided to read the catalog.json. 
    1. 1st file will be a "FeatureCollection" file with all succeeded granules named "successful_features.json"
    2. 2nd file will also be a "featureCollection" file with all failed granules named "failed_features.json". 
3. User will receive a json string in STAC catalog format pointing to above files similar to the "catalog.json" that is provided at the beginning of "stage-out". 
4. User can examine the "failed_features.json", and re-run stage-out again. But that's outside UDS scope. 
    1. "successful_features.json" should be moved to somewhere to avoid being overwritten on 2nd attempt. 
    2. Or we can append timestamps to keep the names unique. 
5. User needs to read all "succeeded_features.json" files and combine them into 1 single "FeatureCollection" which will be the input to the next step, "Catalog to Cumulus via CNM".
