### ISSUE TITLE
Update stage-out to take as input OUTPUT_DIR

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#258]
This PR https://github.com/unity-sds/unity-data-services/pull/253 introduced the following outputs

- catalog.json
- successful_features.json
- failed_features.json

These files are currently written to the input catalog.json directory.

To separate out the inputs to the tasks and outputs from the task, take as input an OUTPUT_DIR variable and write these 3 files to OUTPUT_DIR.

**Comment by wphyojpl** [comment]
Hi @ngachung ,
I'm checking out the catalog.json
Would you like additional ENV named `OUTPUT_DIR`? If so, I guess it can be absolute path or relative path from the folder of catalog.json
or 
Would you have additional `item` in `catalog.json`? 
```
{"rel": "item", "href": "absolute path or relative path from the folder of catalog.json", "type": "application/json", "title": "output_dir"}
```

**Comment by ngachung** [comment]
Duplicate of newer ticket https://github.com/unity-sds/unity-data-services/issues/318
