### ISSUE TITLE
Update stage-in to support STAC_JSON being a remote URL

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#285]
STAC_JSON currently supports loading STAC from a local file and a string. New request to also support loading STAC from a remote URL.

**Comment by wphyojpl** [comment]
Hi @ngachung @mike-gangl ,
Is it possible to have example URLs that I can use to test this? 
Probably a DAAC URL that's behind password. 

Thanks.

**Comment by ngachung** [comment]
For now we will assume that the remote request for STAC response does not require login.
