### ISSUE TITLE
Deploy UDS to MCP shared services PROD

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#286]

**Comment by mike-gangl** [comment]
Can you provide an update on this ticket?

**Comment by ngachung** [comment]
UDS v5.7.1, Cumulus v18.0.0 has been deployed to PROD.

The following urn prefix is defined `urn:nasa:unity:sbg:dev:.*`

API Gateway: `https://fzubxq882m.execute-api.us-west-2.amazonaws.com/prod/am-uds-dapa/`

ClientId: `7vehllplbone6p4usqgutqun35`
