### ISSUE TITLE
Provide notebook tutorial for registering custom metadata

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#289]
Tutorial for end user (admin permission) to create a custom metadata field.
Tutorial for how to include custom metadata value in STAC.

**Comment by GodwinShen** [comment]
@ngachung I see you have this scheduled for 24.1.3.  Is this on track to complete in the current 24.1.3 sprint?

**Comment by ngachung** [comment]
Work has not started for this. Will push to 24.1.4.

**Comment by ngachung** [comment]
Awaiting review / merged of https://github.com/unity-sds/sounder-sips-tutorial/pull/54
