### ISSUE TITLE
Deploy STAC Browser in dev environment

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#292]

**Comment by GodwinShen** [comment]
@ngachung is this really a 24.1.5 task?  It seems like we were starting to make progress on a related ticket (https://github.com/unity-sds/unity-project-management/issues/117) so if we're working this ticket then I would like us to re-allocate it to the current 24.1.2 sprint and status it accordingly.

**Comment by ngachung** [comment]
Moved to 24.1.3 sprint.

**Comment by rtapella** [comment]
- part of https://github.com/unity-sds/unity-project-management/issues/117

**Comment by wphyojpl** [comment]
```
catelog.json  (root level)
    - links
        - child: collection
        - child: collection
        - child: collection

collection.json  (a single collection)
    - links
        - items: FeatureCollection

feature_collection.json (for multiple granules)
    - features
        - feature / granule
```

===
Current Responses from Collection & granule queries:
```
feature_collection.json for Collections
    - features
        - collection
            - don't ahve "items: FeatureCollection for granules"

feature_collection.json (for multiple granules)
    - features
        - feature / granule
```

**Comment by ngachung** [comment]
Based on William's findings, we need to make the following changes to UDS responses before we can integrate with STAC Browser

https://github.com/unity-sds/unity-data-services/issues/331
https://github.com/unity-sds/unity-data-services/issues/332

**Comment by GodwinShen** [comment]
@ngachung it looks like the two tickets you quoted above (#331 and #332) are done.  Any new progress since then?

**Comment by ngachung** [comment]
STAC Browser configured to accept "bearer token" authentication has been deployed to MCP DEV.
