### ISSUE TITLE
Deploy and test custom metadata changes in MCP DEV

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#294]

**Comment by mike-gangl** [comment]
Can you provide an update on this ticket?

**Comment by ngachung** [comment]
UDS v6.4.2 has been deployed to MCP Dev.

Custom metadata search works. For example, curl command to search for granules with last updated time > 2024-02-04

`curl "https://d3vc8w9zcq658.cloudfront.net/am-uds-dapa/collections/urn:nasa:unity:uds_local_test:DEV1:CHRP_16_DAY_REBIN___4/items?filter=updated%20%3E%3D%20%272024-02-04T00%3A00%3A00Z%27"`
