### ISSUE TITLE
Create data bucket for SBG dev venue

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#298]
- Create a bucket in SBG dev venue s3://unity-sbg-dev-data
- Apply cross account bucket policy to allow UDS Unity PROD deployment access
- Update UDS Unity PROD deployment to include bucket in IAM policies

**Comment by mike-gangl** [comment]
Bucket is created, but we want to ensure the bucket policy is added by U-DS.

**Comment by mike-gangl** [comment]
Can you provide an update on this ticket?

**Comment by ngachung** [comment]
Bucket policy applied and unity-sbg-dev-data added to IAM policies.
