### ISSUE TITLE
Update stac metadata parser to determine correct STAC metadata file

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#301]
This change request is a result of data file being a JSON file.

SISTER_EMIT_L1B_RDN_20240103T131936_001.json (STAC json)
SISTER_EMIT_L1B_RDN_20240103T131936_001.met.json (data file)

Logic for determining STAC json file is as follows:

1. Check first for CNM type = metadata
2. Check that it matches FILE_POSTFIX
3. Then try to read it as STAC feature

**Comment by wphyojpl** [comment]
Will there be the same issue for cas and s4pa metadta parsers?
