### ISSUE TITLE
Deploy the STAC browser in the shared services account and make it reachable

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-data-services#328]

**Comment by ngachung** [comment]
Since we called out deployment in DEV in https://github.com/unity-sds/unity-data-services/issues/292. We'll use this ticket for shared services TEST and PROD.

**Comment by GodwinShen** [comment]
@ngachung I added #292 as a dependency for this one since I assume you'll do the DEV deployment before pushing to TEST and PROD.

**Comment by ngachung** [comment]
STAC Browser with token auth has been deployed to MCP Test and Prod shared services account.
