### ISSUE TITLE
Configure the STAC Browser to use bearer type authentication

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-data-services#329]
- part of https://github.com/unity-sds/unity-project-management/issues/117

**Comment by GodwinShen** [comment]
Thanks @rtapella for creating this ticket.  @ngachung can you please assign this to a sprint so that we can track it on our project board?

**Comment by ngachung** [comment]
Done. Associated PR: https://github.com/unity-sds/unity-data-services/pull/339
