### ISSUE TITLE
UDS to return Collection as top level instead of FeatureCollection for /collections/[collection ID]

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#332]
Include also /items in links array for collection

**Comment by wphyojpl** [comment]
This endpoint won't be a search. It will just return a single collection based on its ID.

**Comment by wphyojpl** [comment]
If we want it backward compatible, 
- `/collections` return Feature collection of collections. 
    - `/collections` can also return a catalog which breaks backward compatibility. But it might needs a pagination. I'm not sure how that would work with stac browser. 
- `/collections/{id}` return a Collection
