### ISSUE TITLE
Add health check endpoint for U-DS catalog

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#351]
Create an SSM parameter following UCS provided naming convention `/unity/healthCheck/<MARKETPLACE_ITEM>/<COMPONENT_NAME>/url` and store [cloudfront]/am-uds-dapa/collections endpoint as URL

For UDS SSM parameter name will be /unity/healthCheck/shared-services/data-catalog

Assumptions:

- UCS is able to provide Cognito auth when hitting endpoint
- UCS will propagate the SSM parameter from shared service into venue accounts (TBC)

**Comment by wphyojpl** [comment]
Hi @ngachung 

Is this `/unity/healthCheck/<MARKETPLACE_ITEM>/<COMPONENT_NAME>/url` enough? 
In DEV, we have sbx and dev. 
Both would end up in the same SSM param. 
I guess other environments would only have 1, but there can be more than 1 in theory.

**Comment by ngachung** [comment]
Let's assume there is one. For dev we would populate SSM but for sbx we would not, so optional SSM.

**Comment by ngachung** [comment]
The following SSM parameter `/unity/healthCheck/shared-services/data-catalog/url` is now avaiable in shared services dev, test, and prod.
