### ISSUE TITLE
Create data bucket in EMIT dev venue

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#352]
Depending on when this is required by, we may be able to leverage marketplace deployment.

Blocked by MCP creating new EMIT account
https://github.com/unity-sds/unity-project-management/issues/151

**Comment by GodwinShen** [comment]
@mike-gangl what's the status of the EMIT venue?  Have we heard back yet from MCP?  I'd be curious to know the time it takes them to create this new venue...

**Comment by ngachung** [comment]
Bucket created by locally running terraform apply from https://github.com/unity-sds/unity-data-services/tree/develop/tf-module/marketplace to create resources using the below tfvars

```
project = "emit"
venue = "dev"
market_bucket_name = "data"
market_bucket__notification_prefix = "stage_out"
tags = {
  Venue = "dev",
  ServiceArea = "ds",
  Proj = "emit",
  CreatedBy = "ds",
  Env = "dev",
}
uds_aws_account_ssm_path="/unity/shared-services/aws/account"
uds_aws_account_region_ssm_path="/unity/shared-services/aws/account/region"
uds_prefix_ssm_path="/unity/shared-services/data-catalog/deployment/prefix"
cumulus_lambda_processing_role_name_postfix="lambda-processing"
```
