### ISSUE TITLE
Figure out how to add newly created buckets to Cumulus policy

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#360]

**Comment by ngachung** [comment]
Confirmed that we can use wildcard when defining buckets in Cumulus, e.g.

```
buckets = {
  unity = {
    name = "*-unity-*"
    type = "private"
  }
}
```

**Comment by GodwinShen** [comment]
@ngachung does your comment above mean this ticket is done?  I can't tell what the exact scope of this ticket it, that's why I'm asking.

**Comment by ngachung** [comment]
Closing this as done. For now, in the marketplace bucket creation, we will require unity in the bucket name. See https://github.com/unity-sds/unity-data-services/pull/372/files#diff-ba1c4609f057c44631986fdde211009f27ac78316a45769380b28f339f0f4424R12
