### ISSUE TITLE
Schema design and implementation for tracking archive status of a granule

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#380]
Store status, error_code, and error_message.

Successfully publish CNM-S to DAAC SNS, archive_status = cnm_s_success
Failed to publish CNM-S to DAAC SNS, archive_status = cnm_s_failed

Save DAAC CNM-R to s3.
Update STAC item to include s3 url to CNM-R and archive status (cnm_r_success, cnm_r_failed).

**Comment by wphyojpl** [comment]
Hi @ngachung 
What if there are more than 1 daac that 1 granule is being archived? 
```
Successfully publish CNM-S to DAAC SNS, archive_status = cnm_s_success
Failed to publish CNM-S to DAAC SNS, archive_status = cnm_s_failed
```
would not work. 
Should it be a dictionary with daac being the key?
