### ISSUE TITLE
Deploy latest UDS components to prod and populate manifest

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#381]

**Comment by wphyojpl** [comment]
#### Starting stac browser in docker

- Start new EC2
- with this AMI: ami-050f8442c796e93eb
- use t3.medium 
- use security group:  sg-030581d4458221aaa (Although stricter group may also be ok)
- 25GB gp3 storage
- connect using session manager
- Run the following commands
    - `sudo -su root`
    - `/bin/bash`
    - `snap install docker  `
- keep the IP address: example: `10.52.10.210`
- Copy this file: https://github.com/unity-sds/unity-data-services/blob/develop/docker/docker-compose-web-service.yml to EC2
- Update the`image` and `DAPA_API_URL_BASE`
- RUn this command: `docker-compose -f docker-compose-web-service.yaml up -d`
--------------------------------------------
#### Update httpd
- Connect to "shared-services-httpd" using session manager
- Run the following commands
    - `sudo -su root`
    - `/bin/bash`
    - `cd /etc/apache2/`
    - `vi sites-available/unity-cs.conf`
- add / update the following block

```
  ProxyPass "/data/" "http://<IP address>:8005/data/"
    ProxyPassReverse "/data/" "http://<IP address>:8005/data/"

    <Location /data>
       ProxyPreserveHost on
       AuthType openid-connect
       Require valid-user
    </Location>
```

Example:
```
    ProxyPass "/data/" "http://10.52.10.210:8005/data/"
    ProxyPassReverse "/data/" "http://10.52.10.210:8005/data/"

    <Location /data>
       ProxyPreserveHost on
       AuthType openid-connect
       Require valid-user
    </Location>
```
- reload it
    - `a2dissite unity-cs.conf`
    - `systemctl reload apache2`
    - `a2ensite unity-cs.conf`
    - `systemctl reload apache2`
- NOTE: need to add `https://www.dev.mdps.mcp.nasa.gov:4443` to CORS_ORIGINS in the uds_api lambda environment values.

**Comment by ngachung** [comment]
UDS v7.10.1 deployed to PROD. Manifest updated.
