### ISSUE TITLE
Autocatalog: Deploy auto-catalog functionality to unity-test (shared services)

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#389]

**Comment by mike-gangl** [comment]
Blocked by #381

**Comment by ngachung** [comment]
UDS v7.9.0 has been deployed to shared services test and prod.
Tested auto cataloging feature in shared services test by manually invoking stage-out to upload 3 granules for test collection urn:nasa:unity:unity:test:nga-collection___1
