### ISSUE TITLE
Replace health check SSM

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#397]
https://github.com/unity-sds/unity-data-services/issues/351 has been superseded by new requirements as captured in https://github.com/unity-sds/unity-monorepo/tree/main/schemas/health-service

**Comment by wphyojpl** [comment]
Looks like the key needs to be changed to "/unity/shared-services/component/data-catalog/" and 2 URLs are needed. 
```
{
    "componentName": "Data Catalog",
    "healthCheckUrl": "https:/....",
    "landingPageUrl": "https://..."
}
```
healthCheckUrl can be the public facing API Gateway catalog URL which stac browser uses. 
landingPage can be either api gateway's open API json page or stac browser page.

**Comment by wphyojpl** [comment]
healthCheck is collections URL (let UCS figure out how to pass creds). landingPage is stac browser.

**Comment by wphyojpl** [comment]
This is the result.
```
{"componentName":"Data Catalog","healthCheckUrl":"https://d3vc8w9zcq658.cloudfront.net/data-sbx/collections","landingPageUrl":"https://www.dev.mdps.mcp.nasa.gov:4443/data/misc/stac_entry"}
```
But it cannot end with `/`
