### ISSUE TITLE
Push UDS libraries to pypi

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#417]
https://github.com/unity-sds/unity-py gets pushed to https://pypi.org/project/unity-sds-client/

We would also like to expose UDS libraries so users can invoke stage-in, stage-out directly in Jupyter notebooks.

Need to think of a name for the package

**Comment by wphyojpl** [comment]
This is done. 
https://github.com/unity-sds/mdps-ds-lib and https://pypi.org/project/mdps-ds-lib/
