### ISSUE TITLE
As a project, I want to be able to dynamically create data collection catalog entries at ingest time and not predefine them so that new and test products can be created ad hoc

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-data-services#43]
The scenario here is that many different products might be iterated on for various collections (pre-release versions) and to create each of these in advance would be very difficult.

**Comment by ngachung** [comment]
Collection is created if it does not exist during ingest https://github.com/unity-sds/unity-data-services/blob/develop/cumulus_lambda_functions/granules_cnm_ingester/granules_cnm_ingester_logic.py#L191
