### ISSUE TITLE
Single catalog for granules in multiple collections

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#432]
Requires collection in stac.json to be a legitimate unity collection
Question: Would we still want to support single COLLECTION_ID environment for stage out?

**Comment by wphyojpl** [comment]
I think this is fixed by https://github.com/unity-sds/unity-data-services/issues/437
Since we are getting collection id from granules stac, we don't care if they are the same.

**Comment by wphyojpl** [comment]
Actually, we have to update our automated ingestion to create multiple collections..
