### ISSUE TITLE
Add pagination links to STAC response of DAPA endpoints

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#66]

**Comment by mike-gangl** [comment]
This should follow the best practices described here:
https://github.com/radiantearth/stac-spec/blob/789e90fba4c7119bc925d26f75f47bacf44c91e6/best-practices.md#using-relation-types 

i wonder if we should have a separate issue for making the STAC response follow the 'stac-spec' ? 
https://stacspec.org/en/about/stac-spec/

**Comment by wphyojpl** [comment]
#70 is merged.
