### ISSUE TITLE
Evaluate Cumulus data model with respect to satisfying Unity requirements

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#8]

**Comment by seanhardman** [comment]
Cumulus may not be the permanent solution for managing data ingestion, but its associated data model plays nice with CMR/UMM. Requirements UNI-REQ-317 and UNI-REQ-318 are associated with interfaces to an ingestion interface but they do reference cataloging metadata pertaining to ingesting of science data files and their associated files. In addition, requirement UNI-REQ-320 is associated with capturing minimal provenance information. These three requirements are satisfied by the Cumulus data model. The one outlier cataloging requirement is UNI-REQ-321 pertaining to capturing a more detailed set of provenance metadata. The Cumulus data model doesn't support this more detailed metadata but it will be captured in the Unity DS Data Model.
