### ISSUE TITLE
[Bug]: DAPA collections endpoint returns incorrect temporal interval in STAC response

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#86]
Current implementation for retrieving granule extent uses Cumulus /stats API https://nasa.github.io/cumulus-api/#summary but it turns out that the dateFrom and dateTo in the response corresponds to user provided time range and not the granule extent. The use of /stats is to get back total granule count for a user provide time range.

To retrieve granule extent for each collection UDS can either 
1. Query Elasticsearch directly (ES may not be supported by future version of Cumulus)
2. Query RDS directly
3. Invoke /granules for each collection twice and sort by time asc, desc to get date (costly for lots of collections)

**Comment by wphyojpl** [comment]
```
select c.name, c.version, count(g.cumulus_id), min(g.beginning_date_time), max(g.ending_date_time) from public.collections as c left join public.granules as g on c.cumulus_id = g.collection_cumulus_id group by c.name, c.version
```

**Comment by ngachung** [comment]
Duplicate of https://github.com/unity-sds/unity-data-services/issues/64
